### ISSUE TITLE
How to play local vr vedio with SDK

### ISSUE THREAD

**Issue by xm007forgithub** [googlevr/gvr-android-sdk#108]
I want to play local vedio with SDK, but the SDK just offer two methods：assets and uri 。I get the vedio'id from the media database and get a uri with Uri.withAppendedPath(MediaStore.Video.Media.EXTERNAL_CONTENT_URI, String.valueOf(id)),  content://media/external/video/media/24825 .How ever, VrVideoView.loadVideo(uri) made a error 
java.io.FileNotFoundException: /external/video/media/24825: open failed: ENOENT (No such file or directory).I don't know why. My local vedio's path is /storage/sdcard0/congo.mp4. I use some phone to test , I found that if the phone's sdcard root path is '/mnt/sdcard' , this SDK can work;but if the phone's sdcard root path is '/storage/sdcarad0',this sdcard will cannot work.

**Comment by nihalmehdi** [comment]
workaround that works for me..probably you need to get image from databases instead of web hosted..

public class DownloadVideoTask extends AsyncTask {
String videoUrl ="http://host/test.mp4"
private VrVideoView vrvideoView;
private Context context;
DownloadVideoTask (VrVideoView vrvideoView,Context context)
{
this.vrvideoView = vrvideoView;
this.context = context;
}

@Override
protected Uri doInBackground(String... url) {
    //HttpsURLConnection.setDefaultSSLSocketFactory(new NoSSLv3Factory());
    HttpURLConnection urlConnection = null;
    String fileName = "test.mp4";
    String filepath = context.getFilesDir() + File.separator + fileName;
    File file = null;
    try {
        URL videoUri = new java.net.URL(videoUrl);
        urlConnection = (HttpURLConnection) videoUri.openConnection();
        urlConnection.connect();
        InputStream in = urlConnection.getInputStream();
        FileOutputStream output = context.openFileOutput(fileName, context.MODE_PRIVATE);
        Utility.copyFile(in,output);
    }
    catch (java.net.MalformedURLException mex){
        String test = mex.toString();
        //Toast.makeText("Utility", mex.getMessage(), Toast.LENGTH_LONG);
    }
    catch (Exception ex)
    {
        String test = ex.toString();
        //Toast.makeText("tag",ex.getMessage(),Toast.LENGTH_LONG);
    }
    finally {
        if( urlConnection!= null ) {
            urlConnection.disconnect();
        }
    }

    return Uri.parse(filepath);
}

public String getVideoUrl() {
    return videoUrl;
}

@Override
protected void onPostExecute(Uri videoUri) {
    try {
        vrvideoView.loadVideo(videoUri);
        vrvideoView.playVideo();
    }
    catch (Exception ex){
        String msg = ex.getMessage();
        //Toast.makeText(this,"Test",3000)
    }

}
}

Utility method-
public static void copyFile(InputStream in, OutputStream out) throws IOException {
        byte[] buffer = new byte[1024];
        int read;
        while((read = in.read(buffer)) != -1){
            out.write(buffer, 0, read);
        }
    }

**Comment by dav-cz** [comment]
@xm007forgithub, did you try adding a "file:///" prefix to your local URIs? e.g. "file:///sdcard/FILENAME.MP4"

**Comment by dav-cz** [comment]
Closing this bug -- using a "/sdcard/FILENAME.MP4" or similar path should now work with v0.8.1 without adding a "file:///" prefix. 
Please re-open if you still see this issue.
