### ISSUE TITLE
Remote streaming of stereoscopic videos

### ISSUE THREAD

**Issue by BrendanParks** [googlevr/gvr-android-sdk#112]
I've found remote streaming of stereoscopic videos (for viewing inside a Cardboard headset) is not supported. Are there any forthcoming plans to add this feature? Thanks!

**Comment by dav-cz** [comment]
Hi @BrendanParks, did you check VrVideoView? It lets you stream 360 videos (e.g. http://domain.com/file.mp4) in VR that you can view inside a Cardboard headset.

**Comment by grobm** [comment]
@dav-cz I assume this is not only public media paths but supports tokenized paths as well?

**Comment by dav-cz** [comment]
This only supports public media paths officially. It's backed by ExoPlayer though, so the answer to that issue https://github.com/google/ExoPlayer/issues/625 might work  -- making sure all HTTP connections use the same cookie store, potentially by installing a default cookie manager. I haven't tried, though.

**Comment by azeemmohd** [comment]
It doesn't support live playback of .m3u8 streams, just a remote video hosted on a public media path.

**Comment by dav-cz** [comment]
@azeemmohd. With v0.8.1 VrVideoView now supports HLS streams, you can check the SimpleVrVideoActivity.java sample to see how to use it.

@grobm, were you able to look at VrVideoView and see if it can fit your needs? If not, it'd be great to know what's missing. Thanks!

**Comment by digitalbuddha** [comment]
hi @dav-cz I posted this in a closed issue.  We're trying to implement VrVideView in NY Times app, I'm having trouble playing a remote video due to inability to buffer.  The video in question is: `http://video1.nytimes.com/video/360-demo/cool.mp4`

When I drop the video in as a static asset everything plays perfectly. When trying to stream, the video stops and does not start on its own again.  Is there a way to control how much is download before starting as well as general buffering strategies?

The only code change I made to SimpleVrVideoActivity is to change the url in async task to `        videoWidgetView.loadVideo(Uri.parse("http://video1.nytimes.com/video/360-demo/cool.mp4"),new Options());`

I see that there's some generated code that deals with exoplayer, maybe there are more hooks that can be exposed?

**Comment by arumani** [comment]
Hi @dav-cz. I have the same problem with @BrendanParks.
"congo.mp4" in samples/simplevideowidget is "Spherical and 3D Top-bottom" video. And it's ok when I drop the video in as a static asset. But when trying to stream ( http://s3.amazonaws.com/googlevr-test/congo.mp4 ), it seems as below. Maybe the video is processed as "Spherical and NOT 3D".

![screenshot_2016-06-24-23-38-04](https://cloud.githubusercontent.com/assets/1302700/16343633/3a221012-3a73-11e6-9f64-4f94719c32db.png)
![screenshot_2016-06-24-23-38-14](https://cloud.githubusercontent.com/assets/1302700/16343632/3a1ec13c-3a73-11e6-8055-1466aecfd251.png)

**Comment by dav-cz** [comment]
@arumani You're right, currently remote videos are assumed to be spherical AND monocular. There's currently no way to specify that the remote video is spherical and 3D (i.e. with top-bottom frames for left and right eyes). This will be added soon via the VrVideoView.Options object.

**Comment by arumani** [comment]
@dav-cz Thanks for your reply. I'm looking forward to it !

**Comment by dav-cz** [comment]
Feature added in 0.8.5.

See how the sample video app was updated, you can now specify the video type (mono vs stereo over under):

```
Options options = new Options();
options.inputType = Options.TYPE_STEREO_OVER_UNDER;
```

**Comment by bsmith42** [comment]
Any future option to add TYPE_STEREO_PARALLEL_VIEW (for side by side video vs. over_under)?

**Comment by nathanmartz** [comment]
We don't currently plan to add SxS stereo support as we are standardizing on over/under for 360 stereo.

**Comment by bsmith42** [comment]
Thanks for the quick response!  I brought it up since Ricoh Theta uses it.
