### ISSUE TITLE
Disable tutorial screen that says "Place your phone into your Cardboard viewer."

### ISSUE THREAD

**Issue by dosa1127** [googlevr/gvr-android-sdk#118]
Hi, is there any way we can disable the tutorial screen that says "Place your phone into your Cardboard viewer." from showing up? Thanks!

**Comment by nathanmartz** [comment]
This is very much intentional. User studies suggested that without this screen users often don't know what to do.

**Comment by xdf103** [comment]
We understand that it is intentional to have the tutorial screen, but it could become annoying as users have to see it on every screen. Is it possible to disable/hide it, or configure it to display only once?

**Comment by nathanmartz** [comment]
It should only appear on the first run, then you pair a viewer, then you should not see it again (unless you uninstall and reinstall the app, possibly including development pushes).

**Comment by xdf103** [comment]
I have two activities, a play list activity (a simple ListView) and a play activity (using GvrView). Every time I go from the play list activity to the play activity, I see the tutorial screen, e.g. list activity -> play activity (tutorial screen appears) -> go back to list activity -> play activity (tutorial screen appears again) . How do I configure it to appear only once?

**Comment by nathanmartz** [comment]
By "tutorial" you mean the "place your phone into the cardboard" or the
"please scan a cardboard" screen? If it's the former, that's by design.

**Comment by xdf103** [comment]
I mean "place your phone into the cardboard" screen

**Comment by xdf103** [comment]
Is there any way to disable/hide it?

**Comment by nathanmartz** [comment]
No. See my original comments.

**Comment by xdf103** [comment]
We encountered another problem with "place your phone into the cardboard" screen. Our workflow is list activity -> play activity -> back to list activity. For the 2nd step play activity -> back to list activity, we now have to press the back button twice. Press once, it will show the "place your phone into the cardboard" again and continue to the play activity again. Only after two presses, it will go back to the previous activity (the list activity). This is inconvenient and seems illogical. Is there anyway to fix this?

**Comment by nathanmartz** [comment]
Hmm. That seems bad. The transition screen should only appear when entering
VR, not exiting it. We'll look into this...

**Comment by xdf103** [comment]
@nathanmartz please ignore that issue. I found out it was our problem, not an issue in GVR. However, we found the transition screen a bit annoying. Both our activities (the list activity and the play activity) use GvrActivity. When the user first start list activity, he sees the transition screen. After that every time he chooses a video to play, he will see the transition screen. It would be good if the SDK can give us the control to decide when to show the transition screen, otherwise we may have to write our own SDK.

**Comment by nathanmartz** [comment]
The general idea of the transition screen is that it should appear every time the user goes from 2D into VR to ensure users understand how to insert their phone in the viewer. You'd be amazed at how often people misunderstand this idea, turn things the wrong way, etc. The screen disappears as soon as the phone is in landscape, so it's not actually obtrusive IMHO. Are you seeing the screen during VR->VR transitions rather than 2D->VR?

**Comment by xdf103** [comment]
Yes. We are seeing the screen during VR-VR transactions, i.e. going from one GvrActivity to another GvrActivity.
