### ISSUE TITLE
Touch to pan? 

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#132]
Is there a way to enable touch to pan?  Using other Web sdks through a webview works, is there a way to get gvr to pan when I drag the screen around? Thank you kindly.

**Comment by nathanmartz** [comment]
There is not currently but it's a popular request. We're planning to add it for a release later this summer.

**Comment by gary-domain** [comment]
Here's some unsupported hacks:
https://gist.github.com/gary-domain/0a455ee35eaba6da7591e09627d2d1f2

Or simply:
TrackingSensorsHelper.enableTouchTracking = true;
Before initiating the view.

This has some side affects (i.e. hides the VrButton). 
Which seems to get offset by:
TrackingSensorsHelper.showVRModeButtonForTesting = true; 

But yeah, these are hacks.

**Comment by digitalbuddha** [comment]
Thank you much! Will try in am

**Comment by gary-domain** [comment]
Also other side affects are, enableTouchTracking = true will make the method the internal method this.sensorsHelper.areTrackingSensorsAvailable() become false at all times which from I can see affects ViewRotator class. So far I can't see massive issues though. And also I'm not sure what other classes access that variable.

So I think using my gist is probably safer, that way you keep the functionality of areTrackingSensorsAvailable() in tact.

Also note that this obviously has been done by design by the team and I'm sure there's reasons for it so, expect it to be buggy:
if(this.sensorsHelper.areTrackingSensorsAvailable()) {
   touchTracker.setTouchSpeed(0.0F, 0.0F);
}

**Comment by digitalbuddha** [comment]
Would you happen to know if the gist would work for video view too?

**Comment by gary-domain** [comment]
The gist itself wont. It should in theory since they extend the same base class. You'll have to repeat the same process.

I.e. create a new class that extends videoview in that same package.
public class TouchEnabledVrVideoView extends VrVideoView {

Haven't tested it though.

**Comment by dav-cz** [comment]
(Re-opening this until we add official support for it)

**Comment by electmk** [comment]
@dav-cz 
When is the next update ??

**Comment by zhangleiuser** [comment]
I also have this problem, hope to add the pan gesture as soon as possible!

**Comment by electmk** [comment]
@dav-cz 
Will there be support soon ? Or delayed for a long time ?

**Comment by dav-cz** [comment]
We're working on it. It should be there in the next version which we plan to push within 2, 3 weeks.

**Comment by electmk** [comment]
@dav-cz 
Have you been support now on SDK v0.9.0 ?
And how i know what's new on each update ?

**Comment by dav-cz** [comment]
Yes this was implemented in v0.9.0, you can check out release notes here:
https://developers.google.com/vr/android/release-notes

**Comment by ghenzhimura** [comment]
is touch tracking disabled by default in v1.0.1? how to enable it again? @dav-cz
