### ISSUE TITLE
error converting bytecode to dex

### ISSUE THREAD

**Issue by electmk** [googlevr/gvr-android-sdk#148]
I get this error
https://drive.google.com/file/d/0B6wxiaPnUDo4S1NNSlNYUXBoWGc

**Comment by sigmaxipi** [comment]
This is due to [duplicate protobuf libraries](https://github.com/googlevr/gvr-android-sdk/issues/81) in GVR and other apps. If you're manually the protobuf library, you can remove it from your build file. If another .aar is including it, then you will need to edit the classes.jar inside the .aar and delete the duplicate classes in one of the .aars

**Comment by electmk** [comment]
@sigmaxipi 
How i can know the duplicate classes to delete it ? and how edit .aar file ?
If you have any tutorial or explained

**Comment by sigmaxipi** [comment]
An .aar file is just a standard .zip file so you can use normal zip programs to extract files from it and add new files back in. The classes.jar file in it is also a standard .jar file which contains many .class files. You will need to extract the classes.jar from common.aar. Then delete all the .class files in that .jar that cause errors (note the class name in the error message) which should be everything under com/google/protobuf. Then put the modified classes.jar back into the common.aar

**Comment by digitalbuddha** [comment]
This is second issue of this type. Same problem with exoplayer. Is there any reason why gvr has to be a fat jar?
