### ISSUE TITLE
How to disable Distortion Correction when use VrVideoView to play 360 video?

### ISSUE THREAD

**Issue by WeixiangZhang** [googlevr/gvr-android-sdk#155]
The default Distortion Correction has no right effect on some Phone, e.g Meizu with 5.5' 1080p display.

I want to disable Distortion Correction or adjust Distortion Correction parameters to get better effect.

**Comment by dav-cz** [comment]
We don't plan to offer an option to disable distortion correction. Disabling it wouldn't help either, as the problem is probably that this phone is reporting a bad DPI. Hence the SDK doesn't position the center of the two views at the right place. 

Could you run this adb command below, and also report the exact size of your screen? (Is it really 5'5 inches?)

`adb shell getprop | grep "model|manufacturer|hardware|product.name|lcd_density"`

**Comment by WeixiangZhang** [comment]
Thanks for your reply.

Here is output and I am sure the display is 5.5' inches with 1080p resolution.
[ro.boot.hardware]: [mt6735]
[ro.hardware]: [mt6735]
[ro.meizu.hardware.battery]: []
[ro.meizu.hardware.emmc]: [HAG2e]
[ro.meizu.hardware.psn]: [81116E68D802]
[ro.meizu.hardware.version]: [0x57101002]
[ro.meizu.product.model]: [M5710]
[ro.product.manufacturer]: [Meizu]
[ro.product.model]: [m2 note]
[ro.product.name]: [m2note]
[ro.sf.lcd_density]: [480]

**Comment by sigmaxipi** [comment]
If you want a custom videoplayer without distortion, consider using the Video360 sample as a starting point. You can use standard OpenGL to render without distortion. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
