### ISSUE TITLE
Feature Request: RecyclerView multi video support

### ISSUE THREAD

**Issue by digitalbuddha** [googlevr/gvr-android-sdk#166]
Apps like Vine & Facebook offer video playback while scrolling in recycler view.  By default MediaPlayer has problems with UI synchronization while scrolling.  It would be great for GVR SDK to be able to do things like auto play, auto stop, resume videos that are recycling while having smooth playback.

**Comment by sigmaxipi** [comment]
There are no plans to add this functionality since it would be difficult to add in a cross-platform manner and the VrView codebase is meant to be cross platform. If you want to create a custom 360 media player with this functionality, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.
