### ISSUE TITLE
Get HeadTransform from VrVideoView

### ISSUE THREAD

**Issue by JackVerde** [googlevr/gvr-android-sdk#189]
I'm trying to get the HeadTransform from the video player because I need the infos to update my audio spatializer. 

overriding onNewFrame(HeadTransform headtransform) of the CardboardView.StereoRenderer
isnt called when the VrVideoView is present

**Comment by dav-cz** [comment]
With v 0.9.0 there's now [an API](https://developers.google.com/vr/android/reference/com/google/vr/sdk/widgets/common/VrWidgetView.html#getHeadRotation(float[])) to return the head position with yaw, pitch angles.

Closing this since I think that should get you covered. Please re-open if that's not the case.

**Comment by JackVerde** [comment]
@dav-cz thank you for your answer but I'm still not able to call 
"public void getHeadRotation (float[] yawAndPitch)"
from VrVideoView
