### ISSUE TITLE
where did setVrModeEnabled go?

### ISSUE THREAD

**Issue by fcoulombe** [googlevr/gvr-android-sdk#190]
This used to be part of the sdk to use monocular viewport https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setVRModeEnabled(boolean)
and it seems to have gone away in 9.0

AndroidCompat.setVrModeEnabled(this, false);

is still available but it doesn't seem to work

**Comment by jdduke** [comment]
Hi @fcoulombe , sorry for the trouble here. It looks like our Release Notes and API documentation page have yet to be updated (https://developers.google.com/vr/android/release-notes).

In short, we've renamed "GvrView.setVRModeEnabled" to "GvrView.setStereoModeEnabled". This was to disambiguate the feature with the new Android N "VR Mode" feature (wrapped by AndroidCompat.setVrModeEnabled), where the latter is more about enabling VR-releated features on the device rather than toggling mono/stereo mode. Hope that helps!

**Comment by fcoulombe** [comment]
thanks!
