### ISSUE TITLE
SDK 0.9.0: scanline racing vs asynchronous reprojection

### ISSUE THREAD

**Issue by maneets** [googlevr/gvr-android-sdk#218]
Hi,
Using Nexus 6P (N-preview), I recently upgraded app to SDK 0.9.0 release and read this release note:
"Scanling racing" is now referred to as “Asynchronous Reprojection” in the public APIs.

Reading about those 2 terms, it seems like "Scanline racing" is ability to render on front-buffer instead of double buffering to reduce latency which means graphics libraries should support EGL_SINGLE_BUFFER, hence make sense to limit it to Daydream ready phones or Nexus6P at this time.
However, “Asynchronous Reprojection” is a concept of warping frame last minute to correct for delta in latest HMD position. This seems more like software thing as long as GPU is available to perform this.

Questions:
a) What's available in SDK version 0.9.0 - Scanline racing Or Asynchronous reprojection Or both activated via same setAsyncReprojectionEnabled() API ?
b) Why limit Asynchronous reprojection to only Daydream ready phones and reduce app developer's ability to run on more devices?

Thanks for your spending time reading this.

**Comment by nathanmartz** [comment]
Hi, maneets. Good questions. We'll have official docs on them closer to launch, but for now here are your answers...

You're basically right that scanline racing is what lets you write directly to the font buffer. Async reprojection effectively requires scanline racing (otherwise it's not async) but it's the thing that shaves off additional latency by doing additional warping at the last possible moment. Although the concepts are technically independent, we encourage people to think of them as a single unit.

Both scanline racing and async reprojection are available in the 0.9 NDK. We explain how to use the API in this I/O talk: https://www.youtube.com/watch?v=9MIa1lviO_s or you can check out the NDK Treasure Hunt sample.

Scanline racing and async reprojection are not things that you can just "turn on". They require specific features in the kernel, drivers, OS, and SDK to work at all well. Also, high quality smartphone VR isn't just about these two technologies, but also an IMU that can provide high quality head tracking, a sufficiently powerful SoC, etc. That's why the Daydream ready spec exists, because most phones are not, in total, capable of delivering a high quality VR experience.
