### ISSUE TITLE
Treasure Hunt Demo doesn't initiate bluetooth connection to the Controller Emulator

### ISSUE THREAD

**Issue by Hamabama** [googlevr/gvr-android-sdk#223]
Treasure Hunt Demo app doesn't initiate connection to Controller Emulator app. At the same time Painting Demo does it perfectly.

**Comment by nathanmartz** [comment]
Thanks for the bug report. We'll look into it.

**Comment by sigmaxipi** [comment]
This is the expected behavior. The Treasure Hunt samples are meant to be pure Cardboard apps so they don't have Daydream Controller support. Controller Paint was meant to show off the Daydream Controller API so it [uses that API](https://github.com/googlevr/gvr-android-sdk/search?utf8=%E2%9C%93&q=gvr_controller.h).
