### ISSUE TITLE
Usage with ADT instead of Gradle.

### ISSUE THREAD

**Issue by kkszysiu** [googlevr/gvr-android-sdk#224]
Hey guys,

Is there possibility to use this project with ADT, so I will be able to compile everything with ndk-build and then pack it with ant-building system?

I have already existing project and I want to just rebuild it into VR.
My project has lots of dependencies, where I'm building lots of static and shared libs and it seems in Gradle building static and shared libraries it not supported yet.

So are you planning to support ndk-build and ADT in future or add support for building multi dependency NDK projects in Gradle?

Thanks!

**Comment by sigmaxipi** [comment]
We won't support non-gradle builds because it becomes extremely complicated to maintain multiple parallel build systems. Your best option would be to write a preprocessing step that unzips the .aar and reconfigures it to match what your build system expects. ADT is deprecated so your best option is to migrate your project to gradle.

The general Android NDK build system is still in flux, so you'll need to [look at that project](http://tools.android.com/tech-docs/new-build-system) to determine when it will be compatible with your build requirements. The current plan for the GVR NDK is to ship our library code as .so files rather than static libs.
