### ISSUE TITLE
Seeing errors for enableVR while building for Emulator. Nexus_5X_API_23 with Lollipop

### ISSUE THREAD

**Issue by Eulerianial** [googlevr/gvr-android-sdk#247]
Error:(48) No resource identifier found for attribute 'enableVrMode' in package 'android'
Error:Execution failed for task ':samples-sdk-treasurehunt:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\visharma\AppData\Local\Android\Sdk\build-tools\24.0.2\aapt.exe'' finished with non-zero exit value 1

May I know the settings I am missing?

**Comment by chr314** [comment]
https://developers.google.com/vr/android/release-notes
"VR mode" renamed to "Stereo mode"

**Comment by nathanmartz** [comment]
Yes, that's the issue and the fix.

**Comment by Eulerianial** [comment]
But I just cloned the git repository and it was enableVR used in that.
Can we update the Git repo as it doesn't align with instructions given here: https://developers.google.com/vr/android/get-started

**Comment by sigmaxipi** [comment]
You need to compile with SDK 24. The `android:enableVrMode="@string/gvr_vr_mode_component"` referred to in [sdk-treasurehunt/src/main/AndroidManifest.xml](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/AndroidManifest.xml) refers to [R.attr.enableVrMode](https://developer.android.com/reference/android/R.attr.html#enableVrMode) which was added in N.

Make sure to update your SDK in Android Studio so that you have API 24.

**Comment by Eulerianial** [comment]
After switching to SDK24, the APK gives error:

adb shell pm install -r "/data/local/tmp/com.google.vr.sdk.samples.treasurehunt"
	pkg: /data/local/tmp/com.google.vr.sdk.samples.treasurehunt
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]


$ adb shell pm uninstall com.google.vr.sdk.samples.treasurehunt
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APK

**Comment by sigmaxipi** [comment]
You were trying to install an arm build on an x86 emulator. SDK released this week should work without issues.

**Comment by MrCsabaToth** [comment]
@Eulerianial could your resolve this? I'm experiencing the same thing. My phone is Lollipop 5.0 (API 21). I set target SDK everywhere to 24 wherever I could.
