### ISSUE TITLE
lib folder name

### ISSUE THREAD

**Issue by gpx1000** [googlevr/gvr-android-sdk#283]
gvr-android-sdk/ndk/lib has non standard abi naming convention going on.  This prevents using this kind of gradle closure and instead requires a different mechanism to package the files.
android.SourceSets.main.jniLibs {
                srcDirs = [ "../../extern/gvr-android-sdk/ndk/lib" ]
            }

For the standpoint of easy version control it would be nice to not have to perform anything special to use the next version of gvr-android-sdk.  Failing having the .so live inside of an .aar file and having that mechanism work, I'd like to request renaming the files to:
armeabi
armeabi-v7a
x86
x86_64

**Comment by sigmaxipi** [comment]
We are working on fixing this so the NDK samples use the same build system as the SDK Java samples. This will allow them to use a standard dependency statement to pack the .so into the apk by depending on the .aar the way the SDK Java samples do.

**Comment by gpx1000** [comment]
That would be nice, might I also recommend at least publishing a maven public repo?  Naturally, it would make things even easier on both the java and ndk side to be able to simply do this for any new project:

repositories {
maven { url 'https://someurl/public' }
}

dependencies {
compile (name: 'daydream', ext: 'aar')
}

Or something similar to that.  However, it leaves open one hole, which is how to tell cmake / ndkbuild how to link against a so file hanging out in the aar.  Not sure what the easiest way to solve that part of the problem.

**Comment by sigmaxipi** [comment]
Migrating to a repo rather than local .aars is also being worked on. But it's stuck on the issue you mentioned. I don't think there is a good solution to get NDK builds to depend on pure jcenter based aars. I've found various hacks related to depending on exploded jars, but the best option so far is to still ship the .aars in the git repo in addition to jcenter, add an extraction task (shown below) and have the NDK samples depend on the extraction task for the JNI builds while SDK samples can use either local .aars or jcenter libraries.

It should suffice until the gradle system for the NDK gets full aar support.

In root/build.gradle
```
task extractAudioSo(type: Copy) {
    from zipTree("${project.rootDir}/libraries/audio.aar")
    into "${project.rootDir}/libraries/"
    include "jni/**/libgvr_audio.so"
}

task extractGvrSo(type: Copy) {
    from zipTree("${project.rootDir}/libraries/base.aar")
    into "${project.rootDir}/libraries/"
    include "jni/**/libgvr.so"
}

task extractNdk { }
extractNdk.dependsOn extractAudioSo
extractNdk.dependsOn extractGvrSo
```

**Comment by sigmaxipi** [comment]
The .SOs are now supplied via aars and use a more standard build system. It's still not perfect because automatic extraction of an .so from and .aar requires a command line operation.
