### ISSUE TITLE
Daydream category intent filter in Manifest

### ISSUE THREAD

**Issue by mkeblx** [googlevr/gvr-android-sdk#286]
Should `<category android:name="com.google.intent.category.DAYDREAM" />` be added to intent filter for samples?

https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/AndroidManifest.xml

**Comment by jdduke** [comment]
Hi @mkeblx, that's a good observation. The reason we haven't yet added the DAYDREAM category to the SDK's TreasureHunt sample is because it's not (yet) technically Daydream-compatible. That is, it doesn't handle Daydream controller input.

This will be resolved in the next release in several weeks. We've added a simple API to GvrView that Cardboard app developers can use to bootstrap Daydream controller support, making controller button clicks emulate Cardboard trigger events. The release notes will offer details about this new API.

**Comment by mkeblx** [comment]
Great, thanks. Looking forward to next release.

**Comment by sigmaxipi** [comment]
The sdk-treasurehunt sample has now been updated to run on Daydream via the Cardboard emulation mode. See the recent changes for [TreasureHunt.java](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/java/com/google/vr/sdk/samples/treasurehunt/TreasureHuntActivity.java) and its [AndroidManifest.xml](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/AndroidManifest.xml) for more info.
