### ISSUE TITLE
Missing NDK libraries

### ISSUE THREAD

**Issue by mattscar** [googlevr/gvr-android-sdk#308]
The latest offering of the SDK includes NDK sample projects, but doesn't provide the libraries needed to build them, such as libgvr.so.

**Comment by sigmaxipi** [comment]
From the [NDK's Get Started page](https://developers.google.com/vr/android/ndk/get-started#treasure_hunt_sample_app):

> * Extract the NDK .so files by running the command `./gradlew :extractNdk.`
> * In settings.gradle, uncomment the following lines:
>  `include ':samples:ndk-controllerpaint'`
>  `include ':samples:ndk-treasurehunt'`

**Comment by gpx1000** [comment]
Might I suggest in the next SDK release update the extractNdk task to be incremental thus if the libs don't exist it will automatically run just as if there's a new download of the aar it will also correctly run automatically to refresh those libs.

**Comment by mattscar** [comment]
I tried to extract the libraries, but I got an error:

java.lang.UnsupportedClassVersionError: com/android/build/gradle/model/AppComponentModelPlugin : Unsupported major.minor version 52.0

From what I've read online, this means my SDK or NDK isn't current enough. But I've updated both of them as best I can using SDK Manager.

I also tried opening the SDK in Android Studio, and it gave me the following error:

Invalid file: file://.../gvr-android-sdk/libraries/base/build.gradle

It's looking for the build.gradle file in the old libraries/base directory. But that's gone.

**Comment by digitalbuddha** [comment]
I believe this is due to wrong version of Java (JDK)

**Comment by mattscar** [comment]
Sure enough, that did it. Sorry for the bother.

**Comment by jdduke** [comment]
Not a bother at all, we'll try to make the native library extraction more painless/automatic with the next release. Thanks for the feedback.

**Comment by sigmaxipi** [comment]
@gpx1000 the `:extractNdk` task is part of the build dependencies in gradle, but Android Studio doesn't seem to properly recognize these dependencies. If you run `gradlew build`, the `:extractNdk` task will run automatically as part of building the NDK samples. But if you just build from Android Studio, the task will not run and you will get compilation errors.

For the next release, I'll try to streamline it some more but since the NDK + gradle are still experimental, there will probably still be some hacks and hiccups to get .SOs from .AARs.

**Comment by gpx1000** [comment]
@sigmaxipi If I might be so bold as to make a quick suggestion:
Try this:
tasks.whenTaskAdded { task ->
    if (task.name == 'assemble') {
        task.dependsOn extractNdk
    }
}

The command line gradlew build actually builds all tasks where as Android Studio will run a version of Assemble<VariantName><FlavorName><BuildType> to help reduce the amount of time spent building tasks that aren't needed.
Locally, I have gotten the above suggestion to work well for me.
You might also look into migrating to cmake and the stable plugin rather than the experimental.

**Comment by sigmaxipi** [comment]
@gpx1000,  I couldn't get your code to work since Android Studio appears to use :samples-ndk-treasurehunt:assembleFatDebug as the task name. However,
```
build.dependsOn(':extractNdk')
tasks.whenTaskAdded { task ->
    if (task.name.contains('assemble')) {
        task.dependsOn(':extractNdk')
    }
}
```
results in a config that works with both command line gradle and AS builds. 

I will update the SDK to use this dependency if I can't get your suggestion from https://github.com/googlevr/gvr-android-sdk/issues/315 to work. Thanks for the help.

**Comment by gpx1000** [comment]
Happy to help.  And you're right, the name should never equal assemble.  This is what happens when I suggest code off the top of my head; small bugs.
