### ISSUE TITLE
gvr-android-sdk for eclipse?

### ISSUE THREAD

**Issue by Spider100** [googlevr/gvr-android-sdk#317]
Is there any possibility to run this libs in eclipse? My engine is integrated with this IDE so it's realy hard to move on Android Studio.

I've tried to use unpacked * .aar and prepare external libs and after all I've stuck on:

E / AndroidRuntime (3777): Caused by: java.lang.NoClassDefFoundError: com.google.vrtoolkit.cardboard.proto.nano.Phone $ PhoneParams

For now it looks that I will have to use 3 yers old cardboard.jar in my project :(

**Comment by sigmaxipi** [comment]
There are no plans to support Eclipse since Gradle is the build system that Android apps should use going forward. You should migrate your project to Gradle.

Your specific issue is caused by not having the required dependencies in your project. If you look at the SDK dependencies for the [sdk-common](https://github.com/googlevr/gvr-android-sdk/blob/master/libraries/sdk-common-1.10.0.pom) library, it says it requires the protobug-javanano library. You'll need to get [those libraries](http://jcenter.bintray.com/com/google/protobuf/nano/protobuf-javanano/3.1.0/) and add them to your project. You will need to do this for all the gvr libraries and these dependencies might change in the future. You will also need to make sure you are using the resources and .so files from the .aars or you will get runtime errors.

You'll need to look at the .pom files for all the libraries and their dependencies with each new SDK release.
