### ISSUE TITLE
sdk-videoplayer sample missing source code

### ISSUE THREAD

**Issue by tvkamara** [googlevr/gvr-android-sdk#333]
I noticed an interestingly named sample called sdk-videoplayer appeared in the latest commit. There is however no source code in the folder, only a build.gradle file. Have I missed something or are you perhaps planning on publishing this sample in the next commit?

My goal is just to render a video in a Surface which uses scanline racing. I believe I need to enable the async reprojection in the process but I've been struggling with the "Using video viewports" guide in the documentation. Would the sdk-videoplayer sample possibly do just this or even better is there an easier way to use scanline racing in a SurfaceView?

**Comment by jdduke** [comment]
Hi @tvkamara, good catch. The videoplayer sample will be included in a (near) future release. It should help serve as a guide for using an external Surface for the exact purpose you need, rendering video with async reprojection. We'll update this bug when the sample has been released.

In the meantime, is there any particular part of the "Using video viewports" guide which you feel needs more detail or explanation?

**Comment by sigmaxipi** [comment]
@tvkamara are you rendering DRM video or non-DRM video? These APIs are primarily meant for DRM video in VR or video that needs to render at 60fps while the rest of the VR scene renders at a lower framerate.

**Comment by tvkamara** [comment]
Thank you @jdduke and @sigmaxipi for swift responds. My goal is actually to present a video frame for the user as quickly as possible (research project in a university). So every millisecond counts and I believe using scanline racing I might save a couple. My problem is that the only way I believe this is possible at the moment is to use this GVR API which bundles scanline racing with async reprojection. So at the moment I'm trying to portrait the video frames in a 3D setting using the getting started tutorials as reference. This could be a bit of an overkill for my purposes, please let me know if there is an easier way.

I have no need for DRM. I guess the easiest option for me would be if I could just enable scanline racing in my existing SurfaceView. Anyway, the upcoming sample will probably help me in my task. I noticed the viewports guide also changed a bit in the last update, I haven't tried applying it extensively. My lack of experience in 3D rendering with Android is probably the cause why I failed with the last set of instructions. A complete example would really help.

**Comment by sigmaxipi** [comment]
@tvkamara depending on your setup, using the viewport API might not affect your video rendering latency. You can use [setAsyncReprojectionEnabled](https://developers.google.com/vr/android/reference/com/google/vr/sdk/base/GvrView.html#setAsyncReprojectionEnabled(boolean)) without using the Viewport API. Most of our samples [use it]( https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-treasurehunt/src/main/java/com/google/vr/sdk/samples/treasurehunt/TreasureHuntActivity.java#L214).

Do you actually need the VR functionality or do you just want low-latency 2D video? If so, rendering video to an Android SurfaceView is the fastest way since it skips Android compositing steps. Using a TextureView is the second fastest since it adds an extra frame of latency due to Android compositing. Using the GVR API is overkill unless you want the 1) 3D rendering, 2) head tracking, and 3) distortion correction. Each of these steps adds some latency.

**Comment by tvkamara** [comment]
@sigmaxipi low-latency 2D is my primary goal at this point. I might want to test other scenarios as well, so I'm still interested in the upcoming sample.

Android SurfaceView is what I'm using at the moment. It is fast but I was wondering if it could be even faster with scanline racing or front buffer rendering. I believe a SurfaceView is always at least double-buffered right?

**Comment by sigmaxipi** [comment]
Due to the rendering and distortion step in GVR, SurfaceView will probably be faster for basic video. The latency improvements in VR mode are meant to reduce motion-to-photon latency so they won't have as significant of an impact on video rendering latency. The extra overhead related to rendering the 3D scene might also increase the latency compared to a SurfaceView.

**Comment by jdduke** [comment]
Per the original request, the video player sample is now open source, but please consider the advice of @sigmaxipi for your needs. Thanks.
