### ISSUE TITLE
Any way to set head rotation angles in VrWidgetView?

### ISSUE THREAD

**Issue by Ornolfr** [googlevr/gvr-android-sdk#334]
I've been looking through all the documentation and the only method that I've found is this:
`void getHeadRotation(float[] yawAndPitch)`.
Neither it has a correct name as it gets `void`, nor it is working at all. Giving it different float values didn't make any difference for me in both `VrVideoView` and `VrPanoramaView`.  Is there any way to make it possible to get and set the angles programatically? Thanks in advance.

**Update**: Okay, this method mislead me hard and only now I found out that it writes the values to the parameter. So the question is how to set the values now.

**Comment by Ornolfr** [comment]
#191

**Comment by mjanousek** [comment]
Next revision (with setHeadRotation()) haven't been created. Have anyone information about it? When it would be created?

**Comment by nixbyte** [comment]
I still waiting for this issue to be closed and I'll use setHeadRotation() method in my project

**Comment by tao1** [comment]
I need that feature for Android TV platform

**Comment by sigmaxipi** [comment]
Setting an arbitrary head rotation ended up being complex due to the interactions with rotations from the gyro. There are many edge cases where the interaction does unexpected things.

What are your use cases for this? Two options we're looking at are 1) enable the dev to inject fake panning events (similar to how current touch input works) and 2) a new sample app demonstrating how to implement a custom widget view with gyro + touch input.

**Comment by Cooper6334** [comment]
In my case, I like to let user lie on bed but see forward.
I think this feature only needs setHeadRotationOffset(), but not call setHeadRotation() by myself every time.

**Comment by sigmaxipi** [comment]
@Cooper6334, it's unlikely that VrView will ever support arbitrary pitch offsets that would allow the user to lie back and have the view automatically adjust. The interactions between pitch offsets and gyro poses become too complex for most users due to gimbal lock and non-commutative rotations
Custom yaw would need to be handled on a per-app basis.

For this case 2) would be the best option since you could customize the UI as you desired.

**Comment by Ornolfr** [comment]
@sigmaxipi Imagine a device in VR hub standing in public. Everybody could use it, rotate and leave it with that angle. When the content updates it becomes recentered again, but there is wrong angle from that moment. That's why I need to set the angles. By the way, my use case seems to need to set the angles when the video is loaded, not at runtime. For instance, `VrVideoView.Options` could have two additional float fields `pitch` and `yaw`, and the `VrVideoView#loadVideo()` method could rely on these values.

**Comment by tao1** [comment]
My first use case for Android TV would change head rotation when using direction pad.
Second use case would use a paired phone : head rotation from phone is applied to video playing on tv.

**Comment by sigmaxipi** [comment]
@tao1 Are these use cases mutually exclusive? That is, a user will either be using only a dpad or only a headset to control the TV and not both at the same time? 

@Ornolfr , does your use case use head tracking? Or is it a device fixed in place that is only manipulated through pitch & yaw settings rather than the device's sensor?

**Comment by tao1** [comment]
@sigmaxipi Yes mutually exclusive would be fine

**Comment by Ornolfr** [comment]
@sigmaxipi using head tracking only. I said that users could rotate the device to look at the video in different angles. And I need to set the starting pitch and yaw angles when the video is loaded only.

**Comment by jdduke** [comment]
Hi @Ornolfr, there's an undocumented API which allows touch-based control of the widget view (VrWidgetView.setPureTouchTracking(true)). Will that work for your needs?

**Comment by sigmaxipi** [comment]
If you want more complex touch & gryro controlls, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.

**Comment by AppWerft** [comment]
This issue is two years old. And I don't understand Google and the VR-team. Of course we need a possibility to control the yaw/headrotation. I  see more then one solutions:

1. the left/right edge is north and we use i bool switch (yawFollowsHead or other)
2. inside options (like in web default_yaw)
3. a method in constructor (setHeadOffset(float angle))

We build a touristic AR app and now we say to user: please rotate and if the heading is equal a value we start the VRView, this cannot be the solution!
