### ISSUE TITLE
It is possible to add vertical drag to a VrPanoVidget?

### ISSUE THREAD

**Issue by arnoldcoder** [googlevr/gvr-android-sdk#348]
I checked out the examples and samples. I also build my own project based on this library. But as I tested it with a phone with no gyroscope, I saw that I can drag the view vertically but no horizontally. Could this be somehow set? Am I missing something? or this was not implemented yet?
![2017-01-26 06 38 41](https://cloud.githubusercontent.com/assets/16348740/22322231/27abbb70-e3a3-11e6-82ca-3b4742e1a6f3.jpg)

**Comment by ariviere** [comment]
This issue has also been reported here https://github.com/googlevr/gvr-android-sdk/issues/196

Hopefully we can get a fix soon. I went into the code on earlier versions of the library and it was possible to modify it to add the feature. In fact, vertical drag was disabled on purpose 🙁. But I can't use this fix anymore because this part of the code has been moved to another file written in C.

**Comment by sigmaxipi** [comment]
If you want a more complex touch & gyro controls for a 360 media player, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.

**Comment by Gervil** [comment]
The solution for this is only set this `setPureTouchTracking(true);`
