### ISSUE TITLE
VrPanoramaView is not working after screen orientation changes

### ISSUE THREAD

**Issue by p-fischer** [googlevr/gvr-android-sdk#355]
I tested a couple of screenOrientation modes. I found buggy behavior in every of them. Especially, the UI buttons updating according to orientation but the image being upside down is the most common scenario. This is likely to happen when the screen is rotated by 180°.
I observed this behavior in unspecified, fullSensor, sensorLandscape, userLandscape, reverseLandscape, reversePortrait, userPortrait.
My implemenation is derrived from the simple pano sample.
I'm testing on a Nexus 5.

**Comment by anthonycr** [comment]
This bug is also reproducible using the latest `sdk-simplevideowidget` sample project included in the SDK. Repro steps, tested on Nexus 5X:
1. Open the simplevideowidget app and rotate device into landscape. Embedded player is displaying the video correctly.
2. Rotate the device by 180 degrees. This will not trigger an orientation change and so the Activity and VrVideoView will not be recreated. The embedded player is now displaying the video upside down.

**Comment by Lannylanlol** [comment]
This also happens with my app which integrates the last version of sdk-videowidget:1.30.0.
My app uses orientation sensorlandscape and when I rotate the device, all the layout works fine but the videoView rotates displaying the video upside down.
Any solutions? 
Thanks.

**Comment by anthonycr** [comment]
@Lannylanlol the only solution I have found is to recreate the VrVideoView when the device rotates in increments of 90 degrees. If your activity is recreated on configuration change, then this is taken care of you for 90 and 270 degree rotations, but not 180. In order to recreate it for 180 degree rotations, you need to use an `OrientationEventListener` as follows:

```java
Activity activity;
int oldOrientation;
...
activity = this;
Display display = ((WindowManager) getSystemService(WINDOW_SERVICE)).getDefaultDisplay();
oldOrientation = display.getOrientation();

OrientationEventListener listener = new OrientationEventListener(activity) {

    @Override
    public void onOrientationChanged(int newOrientation) {
        if ((newOrientation - oldOrientation) % 2 == 0 && newOrientation != oldOrientation) {
            // This is a 180 degree rotation, destroy your VrVideoView.
        }
        
        oldOrientation = newOrientation.
    }
}

listener.enable();
```

**Comment by sigmaxipi** [comment]
@anthonycr, this is the best workaround for now. The other option is to limit the Activity to `landscape` rather than `sensorLandscape`.

**Comment by sigmaxipi** [comment]
We've improved rotation handling so these issues should be fixed.
