### ISSUE TITLE
UI thread vs GL thread confusion

### ISSUE THREAD

**Issue by scorpeeon** [googlevr/gvr-android-sdk#369]
So in the latest v1.20.0 version of the SDK the samples-ndk-controllerpaint NDK demo calls a glDeleteBuffers() in OnPause() (through the function ClearDrawing()) and this got me thinking: shouldn't this, like all GL-related function calls happen on the GL thread? Because this native OnPause() and OnResume() is called from the UI thread of the app - they are just called from the Activity's onPause()/onResume(), and not through SurfaceView.queueEvent()).

Am I missing something obvious, or is this a valid concern?

So I checked and in the ndk samples (the other being treasurehunt) the following JNI functions are called from the UI thread:
nativeOnCreate()
nativeOnResume()
nativeOnPause()
nativeOnDestroy()
nativeOnTriggerEvent()

And these are called from the GL thread:
nativeOnSurfaceCreated()
nativeOnSurfaceChanged()
nativeOnDrawFrame()

Which led me to another concern: since these JNI functions work on the same objects but work on different threads (UI vs GL) - is it guaranteed that these UI functions don't run parallel with these GL functions, so they are safe to use without any additional locking mechanism? In most of the cases I can see it should be guaranteed that they don't interfere with each other because of the way the Activity life cycle events work - but in one particular case I'm not so sure: is there's something that guarantees that nativeOnTriggerEvent() (on the UI thread) doesn't run at the same time as nativeOnDrawFrame() (on the GL thread)?

**Comment by jdduke** [comment]
Hi @scorpeeon, thanks for the feedback. These samples have evolved over time, and you are absolutely correct that there are some issues with thread-safety. We'll try to update these to ensure consistent thread-access when necessary..

In particular, the methods 

nativeOnCreate()
nativeOnDestroy()

are fine to invoke from the UI thread (create() because there is not yet any native object, and destroy() because at that point we've stopped the GL thread), but the others ought to occur on the GL thread as you've stated.

**Comment by jdduke** [comment]
This should be addressed in the latest SDK release, thanks again for the feedback!

**Comment by scorpeeon** [comment]
Great, thanks!
