### ISSUE TITLE
ZipException duplicate entry com/google/a/a/a.class

### ISSUE THREAD

**Issue by Lannylanlol** [googlevr/gvr-android-sdk#395]
Hi,
upgrading the sdk-videowidget to 1.40.0, I see this error when I try to run the application:

Error:Execution failed for task ':testAppDivaTeam:transformClassesWithJarMergingForExoplayerDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/a/a/a.class

my build.gradle has the following dependencies:

dependencies {
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.android.support:support-v4:23.2.1'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile 'com.google.android.gms:play-services-cast:8.4.0'
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:mediarouter-v7:23.2.1'
    compile 'joda-time:joda-time:2.3'
    compile 'org.jsoup:jsoup:1.7.3'
    testCompile 'junit:junit:4.10'
    compile 'com.google.vr:sdk-videowidget:1.40.0'
}

Applying the same dependencies in your sample app simplevideowidget, this kind of problem doesn't occur.
Any help?
thanks in advance

**Comment by sigmaxipi** [comment]
This looks like an issue with the GVR build system that is creating sdk-videowidget 1.4. In order to streamline the build system, we baked in some proguarded classes into the .aar. This will cause issues with people who also depend on other libraries that also bake in proguarded classes such as GMS.

You'll need to use 1.3 until we fix our build flow. Sorry for the inconvenience.

**Comment by sigmaxipi** [comment]
This is fixed now.
