### ISSUE TITLE
setAsyncReprojectionEnabled(true) breaks setDistortionCorrectionEnabled(false)

### ISSUE THREAD

**Issue by alexeysuvorov** [googlevr/gvr-android-sdk#398]
Hello, we found that on Nexus 6P and Pixel code below called in OnCreate method make phone show black screen. We can hear sound on background, but not image.

```java
if (gvrView.setAsyncReprojectionEnabled(true)) {
      AndroidCompat.setSustainedPerformanceMode(this, true);
}
gvrView.setDistortionCorrectionEnabled(false);
```

It works ok on Nexus 5 and all Samsung we have (probably because gvrView.setAsyncReprojectionEnabled has no means on this phones).

Once we don't call setAsyncReprojectionEnabled(true) - we can see expected image with no distortion correction.

**Comment by sigmaxipi** [comment]
`setDistortionCorrectionEnabled` is meant for very low end Cardboard devices where the GPU isn't fast enough to correct distortion. It should almost never be used because it will result in a bad user experience. `setAsyncReprojectionEnabled` is meant for Daydream Ready devices and will result in a completely different render path than Cardboard render path. 

The proper behavior here should be that `setDistortionCorrectionEnabled` is ignored rather than rendering a black screen, but the two options should never be used together.

**Comment by alexeysuvorov** [comment]
> setDistortionCorrectionEnabled is meant for very low end Cardboard devices where the GPU isn't fast enough to correct distortion

**Comment by alexeysuvorov** [comment]
So, looks like this use case is not valid because of implementation of setAsyncReprojectionEnabled
