### ISSUE TITLE
Transparency in VR panorama pictures

### ISSUE THREAD

**Issue by hc-tronic** [googlevr/gvr-android-sdk#416]
Hi,
I am trying to write a simple AR App, which shows a partially transparent panorama picture (ARGB_8888 format) in front of a camera preview. The VrPanoramaView background is successfully set to transparent (and even the VR symbols). When I load the panorama picture, the transparent areas of the panorama picture are shown in opaque black color.
Is transparency generally supported? If so, what could be my mistake?
Thanks

**Comment by sigmaxipi** [comment]
Transparency is beyond the design of the widgets. If you want to implement something like this, you probably don't need the GVR framework at all since this AR app would only work outside of VR mode. You should look at a plan Android's OpenGL + camera APIs. You can look at `SurfaceTexture` and `GL_TEXTURE_EXTERNAL_OES`  which would let you get the camera preview working in an OpenGL scene as a quad or some other mesh. You would also do something similar with MediaPlayer and render to another texture in OpenGL. Then you could overlay and blend these meshes however you want.
