### ISSUE TITLE
java.lang.RuntimeException: createContext failed: EGL_BAD_CONTEXT

### ISSUE THREAD

**Issue by leocavalcante** [googlevr/gvr-android-sdk#477]
```
09-21 17:53:45.852 3615-3720/com.hellovr E/AndroidRuntime: FATAL EXCEPTION: GLThread 31579
                                                           Process: com.hellovr, PID: 3615
                                                           java.lang.RuntimeException: createContext failed: EGL_BAD_CONTEXT
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1226)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1217)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$EglHelper.start(GvrSurfaceView.java:1051)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$GLThread.guardedRun(GvrSurfaceView.java:1479)
                                                               at com.google.vr.ndk.base.GvrSurfaceView$GLThread.run(GvrSurfaceView.java:1323)
```

Help?

**Comment by nathanmartz** [comment]
What device and what version of the sdk are you using?

On Sep 21, 2017 1:58 PM, "Leo Cavalcante" <notifications@github.com> wrote:

09-21 17:53:45.852 3615-3720/com.hellovr E/AndroidRuntime: FATAL
EXCEPTION: GLThread 31579
                                                           Process:
com.hellovr, PID: 3615

java.lang.RuntimeException: createContext failed: EGL_BAD_CONTEXT
                                                               at
com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1226)
                                                               at
com.google.vr.ndk.base.GvrSurfaceView$EglHelper.throwEglException(GvrSurfaceView.java:1217)
                                                               at
com.google.vr.ndk.base.GvrSurfaceView$EglHelper.start(GvrSurfaceView.java:1051)
                                                               at
com.google.vr.ndk.base.GvrSurfaceView$GLThread.guardedRun(GvrSurfaceView.java:1479)
                                                               at
com.google.vr.ndk.base.GvrSurfaceView$GLThread.run(GvrSurfaceView.java:1323)

Help?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlevr/gvr-android-sdk/issues/477>, or mute the thread

**Comment by leocavalcante** [comment]
Samsung S8
SDK v1.30.0

**Comment by jdduke** [comment]
Hi @leocavalcante, does this problem exist with the latest SDK release (1.80.0)?

**Comment by jdduke** [comment]
If possible, either an attached logcat dump or a full bug report (adb bugreport s8_crash.zip) of the issue would be helpful. Thanks.

**Comment by jdduke** [comment]
Without further details or feedback it's hard to troubleshoot this further. We haven't yet been able to repro. If you can provide more data we'll happily investigate further.
