### ISSUE TITLE
VrVideoView show seekBar or imageButton in fullscreen

### ISSUE THREAD

**Issue by ZhangYe135** [googlevr/gvr-android-sdk#488]
How can i add like play imageButton and seekBar on displayMode is FULLSCREEN_MONO or FULLSCREEN_STEREO ?

**Comment by sigmaxipi** [comment]
The VrView widgets are meant as simple 360 viewers for apps that don't have complex requirements for viewing 360 media. If you want 2d-in-VR UI, consider using the Video360 sample as a starting point. See https://github.com/googlevr/gvr-android-sdk/issues/510 for more info.

**Comment by riadhnet** [comment]
the exemple doesn't show how to add any element on top of the full screen , you just mentioned the simple without responding to the issue , i don't think this should be closed

**Comment by sigmaxipi** [comment]
@riadhnet , see https://developers.google.com/vr/android/samples/video360 for information. The second screenshot shows a floating UI in VR.

**Comment by riadhnet** [comment]
Would this work for non daydream compatible phone? Just like VrVideoView?

**Comment by sigmaxipi** [comment]
The sample as written does require Daydream since it uses Daydream-specific functionality like the controller and VR transitions. However, you can remove the Daydream functionality if you want it to work on plain Cardboard.

To do this:

1. Delete the Daydream entries from AndroidManifest.xml
2. Delete the `DaydreamApi` code from `VideoActivity`. This is only used to perform Daydream transitions into VR. You can use standard Android Intents for a Cardboard launch.
3. Create a new version of `VrVideoActivity` that doesn't use `DaydreamApi` or `ControllerManager`. You'll need to use the gaze and tap code from the Treasure Hunt sample instead of the controller input.
