### ISSUE TITLE
How to save the spatialized audio to file?

### ISSUE THREAD

**Issue by 4570235** [googlevr/gvr-android-sdk#524]
I use GvrAudioEngine to play 3D sound and would like to save the spatialized audio result to disk file for later play back. 
Is there any API could do it? Or is there any method to retrieve the spatialized audio PCM data that sent to OpenSL ES or AudioTrack, so that I can save them myself?

**Comment by sigmaxipi** [comment]
This functionality is beyond what the spatial audio API was designed for. Since the audio that is played back to the user depends on their head position, there is way to save it to disk and play it back.

http://smus.com/spatial-audio-web-vr/ and the related code is a good starting point for information how how the spatial audio is generated from the user's head position and basic audio sources.
