### ISSUE TITLE
[FeatureRequest] Being able to chose projection mode for VrWidgetView

### ISSUE THREAD

**Issue by Zanfas** [googlevr/gvr-android-sdk#537]
Hi folks !

I'm discovering the Google VR SDK for Android. Purpose : as an intern, i have to make an app that can read a NON 360° stereo over/under video and display it in a viewer for a CardBoard). 

It appears that the videos played with the VrVideoView are only rendered using a spheric projection. I want to know if it was possible (or if it's planned in a further release) to choose the projection mode and just render the video using a planar projection. 

Thank you for your attention.

**Comment by sigmaxipi** [comment]
The VrVideoView widget is targeted for immersive videos so it doesn't have support for basic planar videos. However, take a look a the [Video360 sample](https://developers.google.com/vr/android/samples/video360). This is a sample built on the standard GVR APIs. It's targeted for Daydream rather than Cardboard since it uses a controller, but you can rip out the Daydream-specific code and use the gaze input from TreasureHunt. 

The sample only renders to a sphere, but the [Mesh.createUvSphere(...)](https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/rendering/Mesh.java) method takes in many parameters. You could use this to create a "plane" that is actually a small subsection of a sphere. I've used that code to experiment with rendering planar 3D movies in VR.

**Comment by Zanfas** [comment]
Okay thank you a lot for your quick answer and your advices. Would you have any interest in a feedback if i get a result ?

[Terrible English text is coming - sorry grammar]
I don't know if i can discuss about that here but i think 360° rendering is not the only way to do immersive videos. There's an interesting (in my opinion) case where you make stereoscopic videos that are a record of what a human see and hear. In this case, you can use the CardBoard to render precisly the human vision and hearing. One application is to make very immersive training videos (with medical operations from the surgeon point of view for example).

That's why the planar projection is needed in my study case and, in my opinion, i think it would be great to have an already built-in viewer that support planar projection with gaze possibilites.

**Comment by sigmaxipi** [comment]
Yes. Please let us know if you have any problems with the video360 sample.

**Comment by Zanfas** [comment]
Okay so using the video360, i've been able to do some planar projection by changing two parameters in the sample (the field of view). Yet, the result was not great and i found a few days ago a solution to display normal stereoscopic videos by using a GvrView and a custom implementation of StereoRenderer.

The cause of my problem was that i did not understand how the Google VR SDK works and how the renderring was done but now it is fine.
