### ISSUE TITLE
Jank inflating UI

### ISSUE THREAD

**Issue by ayogan2** [googlevr/gvr-android-sdk#543]
Hello,

I want to emulate a regular Android app within VR. I'm extending the video-360 sample provided here and have sized VideoUiView in VR to the aspect ratio of a Galaxy S8 device and am inflating what could be considered a regular Android layout with a few buttons and widgets. I'm noticing that when I don't have any imagebuttons on the layout, the rendering rate of the UI is fine. But when I try to include even 3 imagebuttons with light weight images, the 2D UI starts to show severe jank/slow down of refresh rate. Is there a trick to rendering imagebuttons without affecting performance?

**Comment by sigmaxipi** [comment]
You'll have to profile the app's performance using https://developer.android.com/studio/profile/traceview.html, https://developer.android.com/studio/profile/android-profiler.html or https://developer.android.com/studio/command-line/systrace.html

You'll will need to be careful with 2D animations inside VR. Due to the heavy load on the GPU from the VR system, the 2D animation may stutter since it is not in sync with the VR rendering system. 

You should instrument your code and make sure the `View.draw` operations are not happening too frequently. Your `View.draw` and `unlockCanvasAndPost` should only be called when the 2D View has changed. If the texture is large (in terms of number of pixels) then the drawing operation and updating of the SurfaceTexture will use a lot of GPU bandwidth due to the amount of pixels being copied.

If you do need to have some part of your app's 2D Views updating frequently such as an animating spinner, then it would be a good idea to have that animating part run in its own small CanvasQuad so that the amount of pixels that are redrawn each frame is as low as possible.

**Comment by jdduke** [comment]
Feel free to re-open if you find that this is an issue with the SDK or you're having trouble profiling per the suggestions from @sigmaxipi.
