### ISSUE TITLE
SDK doesn't expose user handedness preference for UX-C2

### ISSUE THREAD

**Issue by rawnsley** [googlevr/gvr-android-sdk#571]
The SDK doesn't seem to have a way to access [UserPrefs.ControllerHandedness](https://developers.google.com/vr/reference/android/com/google/vr/ndk/base/UserPrefs.ControllerHandedness). It's only accessible from the NDK if you use GvrLayout, which has a [GvrApi property](https://developers.google.com/vr/reference/android/com/google/vr/ndk/base/GvrLayout.html#getGvrApi()). However, SDK apps use GvrView, which provides no such option.

This prevents us from complying with [UX-C2: App uses hand preference](https://developers.google.com/vr/distribute/daydream/design-requirements#UX-C2)

**Comment by sigmaxipi** [comment]
The ndk/base/GvrLayout.getGvrApi() method should be fully usable from a pure Java application without adding NDK support to your app. The ndk.base vs sdk.base is a historical artifact of how the APIs evolved rather than a limit on which functions can be used from what type of code.

**Comment by rawnsley** [comment]
@sigmaxipi I use [GvrView](https://developers.google.com/vr/reference/android/com/google/vr/sdk/base/GvrView) rather than GvrLayout so I don't have that option. For example, how would you get GvrApi in the [Treasure Hunt sample](https://developers.google.com/vr/android/samples/treasure-hunt)?

**Comment by sigmaxipi** [comment]
It looks like there is no easy way to get the GvrApi from GvrView. We'll add an API for this.

One short-term option is to switch from GvrView to GvrLayout like the videoplayer sample. The general code would be the same. The `GvrView.StereoRenderer.onDrawEye` code would be replaced with the `VideoSceneRenderer.drawScene` and `VideoSceneRenderer.drawEye` code since the NDK API is slightly lower level than the SDK API.

**Comment by rawnsley** [comment]
Thanks @sigmaxipi . I'll try the suggested workaround.

**Comment by sigmaxipi** [comment]
This is fixed in v1.170
