### ISSUE TITLE
Screen tilts 90 degrees in screenOrientation="landscape". (Video360 Sample)

### ISSUE THREAD

**Issue by crakaC** [googlevr/gvr-android-sdk#574]
I want to display fullscreen 360 video but not VR mode.
I specified display orientation="portrait", it will seem ok but the position of status bar is not good for landscape mode.

I tried to fix above issue, some change in PhoneOrientationListener#onSensorChanged
```
Matrix.rotateM(phoneInWorldSpaceMatrix, 0, 90, 1, 0, 0);
if(context.getResources().getConfiguration().orientation == ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE){
    Matrix.rotateM(phoneInWorldSpaceMatrix, 0, 90, 0, 0, 1);
}
```
that's not make sense.

So, what should I do?

**Comment by sewasewa777** [comment]
H

**Comment by ganico** [comment]
> Is there any sample code for this issue, please? I am also looking for this feature of 360 sample.

did you find an answer for this?? or any alternative way to do it?

**Comment by sigmaxipi** [comment]
https://gist.github.com/sigmaxipi/b9d4cbfb3410e5be6c5279f56c09b391 is a patch that demonstrates the basic functionality required for supporting rotation. I haven't tested it in depth, but it appears to support standard rotations.

Due to the complexity of dealing with rotations while rendering 3D or playing video, it's better to make sure your Activity is fixed in one rotation or you will need to perform thorough testing.

**Comment by ganico** [comment]
> https://gist.github.com/sigmaxipi/b9d4cbfb3410e5be6c5279f56c09b391 is a patch that demonstrates the basic functionality required for supporting rotation. I haven't tested it in depth, but it appears to support standard rotations.
> 
> Due to the complexity of dealing with rotations while rendering 3D or playing video, it's better to make sure your Activity is fixed in one rotation or you will need to perform thorough testing.

Thank you so much for the quick response, sorry i'm no expert on GIT terminologies. So when you patch is it on your sample projects or all I need is to get the changes that you did there? currently my reference is this sample "https://github.com/googlevr/gvr-android-sdk/tree/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360" does this sample have that implementation?

Apology for the long message

**Comment by sigmaxipi** [comment]
The patch shows that changes I made to https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/MonoscopicView.java but those changes are not checked in since they haven't gone through thorough testing.

You can download the patch and use [git apply](https://git-scm.com/docs/git-apply) to modify your local copy of the SDK. Or manually apply the changes into  your own app.

**Comment by ganico** [comment]
it worked!! thank you so much!! @sigmaxipi  :)
