### ISSUE TITLE
Unable to activate performance HUD

### ISSUE THREAD

**Issue by ultraaviolence** [googlevr/gvr-android-sdk#582]
Using the SDK for unity, i have searched the web for days now, I have a samsung S7 edge (8.0.0) and i cannot enable the performance HUD on the developer options. I have used the same APK i built on a friends phone (S9 (9.0.0)) and for some reason, it works on her phone. From what I found online the SDK comes from the APK project, not from the phone, so why it does not work in mine and what can I do to solve it

**Comment by sigmaxipi** [comment]
The performance HUD is lives in Google VR Services rather than the SDK. It's designed to work with Daydream apps that need to maintain 60fps rather than Cardboard apps that don't have a strict FPS requirement. The S7 is not Daydream Ready but the S9 is so your friend's phone will show the PerfHUD for Daydream apps and Cardboard apps running in Daydream-compatible mode.

**Comment by sewasewa777** [comment]
G
