### ISSUE TITLE
Project :samples-sdk-controllerclient not found.

### ISSUE THREAD

**Issue by AlphaCircle** [googlevr/gvr-android-sdk#600]
After updating Android studio to 3.3 recently, the gradle sync fails, showing the message of the title. Gradle can't find the "included" directories of sample apps. 

Any idea to resolve this issue?

**Comment by sigmaxipi** [comment]
I managed to reproduce this by setting the `distributionUrl` in my `wrapper/gradle-wrapper.properties` to `4.10.1`. This happens if you upgrade the NDK to [r19](https://developer.android.com/ndk/downloads/revision_history).

In the `settings.gradle` at the project root, try removing everything except the `include ...` lines. We'll update the project to support the newer NDK

**Comment by AlphaCircle** [comment]
Hello sigmaxipi,
Thanks for your answer. I did what you said to me. That works for me.  Just in case, I removed the directory of ".gradle" in my home where all the caches exist. 

Thanks again for your quick help.

**Comment by gmartinsvrf** [comment]
My android studio is running with:

**Gradle Version: 4.10.1
Android Plugin Version: 3.3.0**

and still got that same error.

Solution was to remove **:samples** from every include in **settings.gradle**

**Comment by hannesa2** [comment]
I made it work out of the box https://github.com/googlevr/gvr-android-sdk/pull/602

**Comment by yihanseattle** [comment]
Thanks @sigmaxipi again! I had the same issue when upgrading to NDK r19. You saved my life twice :)
