### ISSUE TITLE
small white bordered circle

### ISSUE THREAD

**Issue by ganico** [googlevr/gvr-android-sdk#608]
![52436995_215675705974068_549726990362476544_n](https://user-images.githubusercontent.com/7714293/53296735-a0a02d80-384d-11e9-9d2e-ba28ce4809e7.png)

did anyone encounter this thing?? I just noticed this, it's located around left part of the 360.. is it possible to hide it? Since it's not included on my original image asset.

**Comment by sigmaxipi** [comment]
That looks like the controller reticle which shouldn't be drawn when using the 2D rendering mode.  Can you try changing https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/rendering/SceneRenderer.java#L252 so that ` reticle.glDraw(...)` is only called if `eyeType != Type.MONOCULAR`

**Comment by ganico** [comment]
@sigmaxipi it worked!! thank you for your quick response ;) I'll post some more question :)
