### ISSUE TITLE
using local image distorted

### ISSUE THREAD

**Issue by ganico** [googlevr/gvr-android-sdk#610]
currently I could load an image but I tried commenting out some of the codes since I keep on getting the error msg ("No URI specified. Using default panorama.") that I think it's related on the instruction on the top part of MediaLoader. Anyway upon doing this I noticed that the 360 image is distorted so I was thinking is it because of the removing of the codes? or may 360 image is PNG not JPG? I attached a screen shot of my code that i'm currently using.
<img width="761" alt="screen shot 2019-02-26 at 09 50 15" src="https://user-images.githubusercontent.com/7714293/53381642-53869d80-39ac-11e9-9f0a-e608a3e056db.png">

**Comment by sigmaxipi** [comment]
How is the image distorted? Does changing the `stereoFormat` help?

**Comment by ganico** [comment]
@sigmaxipi what should I set to stereoFormat?

**Comment by sigmaxipi** [comment]
Try increasing the number of triangles in the sphere to get rid of the waviness: https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-video360/src/main/java/com/google/vr/sdk/samples/video360/MediaLoader.java#L93

The sample media is top-bottom stereo but you may be using monoscopic panoramas which is why they look different: https://developers.google.com/vr/discover/360-degree-media

**Comment by ganico** [comment]
I did several testing I finally got it here:
private static final int DEFAULT_SPHERE_ROWS = **36**;//30;//24;//18;//12;
private static final int DEFAULT_SPHERE_COLUMNS = **72**;//60;//48;//36;//24;
