### ISSUE TITLE
Need jars instead of aars

### ISSUE THREAD

**Issue by findeway** [googlevr/gvr-android-sdk#76]
aar is fine.But I need to provide my library(which has a reference to cardboard libraries) to my client who can not use aars. This is inconvenient,Please help me out! I also tried your version 0.6 of cardboard sdk, which is packed into one single jar. But it doesn't support portrait orientation.
  Maybe cardboard should reference resource file with getResources().getIdentifier() method

**Comment by sigmaxipi** [comment]
[An AAR is a zip file with a well defined structure](http://tools.android.com/tech-docs/new-build-system/aar-format). You could unzip it and repack it if required but this is prone to break in the future.

**Comment by findeway** [comment]
@sigmaxipi Thanks for you reply! But the thing is if I unzip the aar, I'll have to copy the resources manually into the main module which I don't want to. I need to make my library easily used (even for someone who still uses eclipse).

**Comment by sigmaxipi** [comment]
The complexity of managing resources is why we ship .aar files. Otherwise, it becomes tricky to have multiple components with their own set of resources and native files. That was why we switched to .aar files. This is the standard way for all Android projects. Eclipse [is no longer supported](http://android-developers.blogspot.com/2015/06/an-update-on-eclipse-android-developer.html) so you will need a custom workflow to develop in it.
