### ISSUE TITLE
Undocumented wakelock policy causes unexpected screen dimming when the user stands still

### ISSUE THREAD

**Issue by R1ck77** [googlevr/gvr-android-sdk#79]
I investigated the screen wakelock policy of the `CardboardActivity` (after some user reporting unexpected screen dimming after minutes), and it looks like is kept alive by the user's head movement.

This is a **very nifty** feature to have, but it's not necessarily what a user/developer wants, and by not being documented (correct me if I'm wrong), it violates the *"principle of least surprise"*.

Please consider adding a method to the CardboardActivity/View along those lines:

    void setScreenWakelockMode(int mode); 

with different `mode` parameters, like:

    NONE leave the Wakelock to the developer's responsibility
    MOVEMENT for the current behavior
    ALWAYS_ON keep the screen always on

since as it is now, the current policy is an invitation for bugs.

Thank you for your attention, and keep up the good work! 

<hr/>
PS: for those who might be interested, a quick solution for keeping the screen always on, is to add the:

    android:keepScreenOn="true"

attribute to the `com.google.vrtoolkit.cardboard.CardboardView` tag

**Comment by dav-cz** [comment]
Sorry for the delay and thanks for the feedback. Indeed we have an idle detection in the SDK.

As we've learned (sometimes the hard way), adding options for customization in the SDK means a larger API surface, more tests to write, more QA, and over time slower development velocity. So we're trying as much as possible to have default behaviors that make sense for most users. And I think having this activated by default so that the screen doesn't lock while in VR is the right thing to do.

So what about we add documentation describing this behavior, and explain that if developers don't want this behavior they can add the flag you mention to their GvrView -- thanks for taking the time to write this to unlock others btw.

**Comment by R1ck77** [comment]
I think that documenting the feature would fix the problem nicely! 

Even without counting the added complexity that my suggested addition would introduce (and that I didn't foresee before your answer), on second thought the usage scenarios for it would be so limited, that its introduction would be hardly warranted (in particular the option to disable the wakelock entirely made admittedly no sense)...

To further confirm that just documenting is the right call, I found the issue because my app is a virtual cinema, so probably one of the very few types of app where the user is supposed to be mostly still.

Looking forward to update to the new GVR (and maybe give the NDK a go): keep up the good work!

**Comment by nathanmartz** [comment]
Thanks!
