### ISSUE TITLE
onCardboardTrigger getting called in infinite loop (race)

### ISSUE THREAD

**Issue by maneetsingh** [googlevr/gvr-android-sdk#84]
I have defined an Activity that extends CardboardActivity and overrides onCardboardTrigger method to perform certain action on receiving touch events.

Issue is if I touch my phone screen too early as my Activity is getting initialized, there is certain race condition in CardboardActivity that is kicking in, resulting in onCardboardTrigger() method getting called in a loop. Most likely, this is due to some piece of code in CardboardActivity, responsible for calling onCardboardTrigger() made an assumption that it would not called _so-early_.

I am using latest Cardboard SDK for Android v0.7.0 and I see this issue. It's not very frequent to hit this race, but while using my phone, I hit on this race every now and then. Just printed a log in onCardboardTrigger() method and found out it's not due to race in the application but CardboardView since I see that log getting displayed in a loop due to onCardboardTrigger() getting called repeatly.

Could someone from Google Cardboard team please look into this? Thanks for your help.

**Comment by jdduke** [comment]
What side effects does your onCardboardTrigger override have? If it injects (directly or indirectly) touch events into the View hierarchy, or detaches and re-attaches the CardboardView to the View hierarchy, that could in theory lead to an infinite loop.

The CardboardView trigger detection simply listens to MotionEvent's of type ACTION_DOWN, dispatching the call to the trigger listener when such events are detected. Clients can replicate/tweak this detection directly by overriding CardboardView.onTouchEvent().

A potential workaround (without knowing more details about your program) might be to temporarily disable trigger detection by calling CardboardActivity.setConvertTapIntoTrigger(false) in onCreate, then re-enable it on onResume. Again, without knowing what the side effects of our trigger override are, it's hard to prescribe a solution.

**Comment by maneets** [comment]
onCardboardTrigger() override method sets a boolean variable to true. onDrawEye() method checks this boolean variable, if true, loads a different texture and set this variable to false.

My activity class extends CardboardActivity and implements StereoRenderer. CardboardView and Renderer are set in onCreate() method very similar to the way sample TreasureHuntActivity does the initialization.

I would try your suggested potential workaround. But by the way you have explained trigger detection, I don't know why it should work. In the entire application, I never inject touch events, never detach/re-attach CardboardView in hierarchy. setCardboardView(this) is called just once on onCreate() method of my Activity. Thanks for your quick response. Appreciate it!

**Comment by maneets** [comment]
onCardboardTrigger() override method sets a boolean variable to true. onDrawEye() method checks this boolean variable, if true, loads a different texture and set this variable to false.

My activity class extends CardboardActivity and implements StereoRenderer. CardboardView and Renderer are set in onCreate() method very similar to the way sample TreasureHuntActivity does the initialization.

I would try your suggested potential workaround. But by the way you have explained trigger detection, I don't know why it should work. In the entire application, I never inject touch events, never detach/re-attach CardboardView in hierarchy. setCardboardView(this) is called just once on onCreate() method of my Activity. Thanks for your quick response. Appreciate it!

**Comment by maneets** [comment]
Some more information on this:
- Tried workaround of calling setConvertTapIntoTrigger(false) onCreate() and set it to true onResume(), didn't help.
- Tried overriding onTouchEvent() or register touch listener on CardboardView and setConvertTapIntoTrigger(false) in onCreate(), issue is resolved. Only side-effect is https://github.com/googlesamples/cardboard-java/issues/60, so older Cardboard version with magnets are now unsupported.
- Implemented another workaround (would like to remove it as soon as underlying issue is resolved). So if subsequent calls to onCardboardTrigger() is made within 10ms, it cannot be a human touch, so treat it as nop.
- Another observation: Whenever onCardboardTrigger() starts getting called in a loop, it usually lasts for 10-50 seconds and then stops.

If above helps you in identifying issue in Cardboard sdk or my application, it would be great to let us know. Thanks for your inputs.

**Comment by jdduke** [comment]
I haven't yet been able to reproduce the problem locally. A couple clarifying questions:

1. What device model and Android version are you running?
2. Can you reproduce the problem on other phones?
3. When you say "infinite" loop, do you mean that it's literally a loop in which no other activity occurs, only dispatch of onCardboardTrigger()? Or is it simply that the onCardboardTrigger() method is called repeatedly each frame (or repeatedly per frame), but the app is not in a frozen state?
4. Can you reproduce this behavior with the TreasureHunt sample in the SDK?

Thanks, hopefully we can get to the bottom of this.

**Comment by maneets** [comment]
Thanks jdduke for taking out time for this. Here is the required information:

1. What device model and Android version are you running?
Device: HTC One M8
Android version: 5.0.2
2. Can you reproduce the problem on other phones?
Not yet. Tried on HTC M8 and Samsung Note 5.
3. When you say "infinite" loop, do you mean that it's literally a loop in which no other activity occurs, only dispatch of onCardboardTrigger()? Or is it simply that the onCardboardTrigger() method is called repeatedly each frame (or repeatedly per frame), but the app is not in a frozen state?
Latter statement. onCardboardTrigger() getting called multiple times in a frame/repeatedly over frames but app is not frozen.
4. Can you reproduce this behavior with the TreasureHunt sample in the SDK?
Oh, thank you for asking this question. Tested TreasureHunt sample app on same HTC M8, yes I am hitting it often here too and because cardboard trigger is supposed to vibrate phone when hit, HTC M8 vibrates crazily on hitting this issue.

So this would imply that HTC did something wrong while modifying Vanilla Android such that I am hitting this issue with my HTC M8 phone with Cardboard apps? However, Cardboard apps including mine is working fine on other phones. Thanks for your questions.

**Comment by jdduke** [comment]
One more question, I'm assuming this happens regardless of which Cardboard viewer you're using? That is, you can reproduce the issue when the phone is isolated and not anywhere near a Cardboard viewer? Just want to rule out this being related to the magnetometer trigger detection.

It could very well be an issue specific to HTC and/or the M8 phone. I'll see if I can reproduce under the same conditions, thanks for the feedback.

**Comment by maneets** [comment]
Yes, I can reproduce it when the phone is isolated. The fact that I cannot hit it with Samsung Note 5 or Shield Portable suggests a very M8 HTC_Android 5.0.2 issue to me. Thanks for your active involvement here.

**Comment by jdduke** [comment]
Thanks. Another bit that might be helpful is if you could log the stack trace in your onCardboardTrigger() call and post it here, e.g., android.util.Log.w("onCardboardTrigger", Log.getStackTraceString(new Exception()));

As that could spam the logcat if called repeatedly, you could also just throw an exception...
