### ISSUE TITLE
How to build it in Eclipse ?

### ISSUE THREAD

**Issue by 731942771** [googlevr/gvr-android-sdk#96]
I create a project use eclipse , but always build error : `UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.vr.sdk.samples.simplevideowidget2-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.vr.sdk.samples.simplevideowidget2-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libpano_video_renderer.so"
`
help !

**Comment by nathanmartz** [comment]
I'm sorry but Eclipse is no longer supported.

**Comment by 731942771** [comment]
@nathanmartz Eh...... Could you have a try ?

**Comment by sigmaxipi** [comment]
Eclipse isn't supported in our SDK because it can't handle complex libraries which include resources and native code. You should transition to Android Studio as soon as possible.

The issue you're seeing is a missing native lib. Run `unzip APP.apk` on your Eclipse apk and note all the .so files in it. Compare this with a sample built with Gradle. You will need to get **libpano_video_renderer.so** into your APK. The .so is in **libraries/videowidget/videowidget.aar**. You can unzip it and then edit your build process to include it in your APK.

But the specific library and filenames may change in future releases so you may have issues in the future.

**Comment by 731942771** [comment]
@sigmaxipi Thanks a lot, i'll have a try.
